#!/usr/bin/env bash
set -x

# @see https://askubuntu.com/questions/443560/how-do-i-reset-the-colors-of-my-terminal
# without this "reset", IntelliJ git console outputs everything in red color
tput setaf 7
tput setab 0
export FORCE_COLOR=1

# Used in the validation script to figure out what are the changed files
# and what package-specific checks to run
GIT_DIFF_BASE='--cached'
LINT_SCRIPT_NAME='lint:precommit'
TEST_SCRIPT_NAME='test:precommit'

#;
# Execute checks
#"
# shellcheck disable=2155
imports() {
  local __DIRNAME=$(dirname -- "${BASH_SOURCE[0]}")
  source "$__DIRNAME/../infra/devx-and-repo/repo-shell-scripts/run_all_code_checks_without_build.sh"
}
imports