name: Release packages
description:
  Release by specifying a pnpm filter/selector of packages you want to release

inputs:
  AUTORELEASE_BOT_TOKEN:
    description: 'The github token used for release'
    required: true
  autorelease-bot-name:
    description: The name of the bot that will commit during automatic releases
    required: true
  autorelease-bot-email:
    description: The email of the bot that will commit during automatic releases
    required: true
  package-filter:
    description: The pnpm filter/selector of packages you want to release
    required: true
  snapshot:
    description:
      Whether to release a snapshot version or use default strategy of finding
      the next version based on the git commit messages
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: ⚠️ Warning ⚠️
      if: ${{ ! inputs.snapshot }}
      shell: bash
      run: |
        echo '## ⚠️ Warning ⚠️' >> "$GITHUB_STEP_SUMMARY"
        echo 'This workflow may push new commits to the branch' >> "$GITHUB_STEP_SUMMARY"
        echo 'There shouldn'"'"'t be any PRs merged or other actions running in this repo that can commit to this branch.' >> "$GITHUB_STEP_SUMMARY"
        echo >> "$GITHUB_STEP_SUMMARY"
        echo 'You were warned 🫡!' >> "$GITHUB_STEP_SUMMARY"

    - name: Get list of packages packages with new releases
      uses: ./.github/actions/get-releases
      id: releases
      with:
        package-filter: ${{ inputs.package-filter }}
        add-summary: false

    - name: Set git credentials to use for committing & pushing changes
      shell: bash
      run: |
        git config --local user.email "${{ inputs.autorelease-bot-email }}"
        git config --local user.name "${{ inputs.autorelease-bot-name }}"

    - name: ✨Automatically release ✨
      if: ${{ steps.releases.outputs.list-as-names-only || inputs.snapshot }}
      env:
        GITHUB_TOKEN: ${{ inputs.AUTORELEASE_BOT_TOKEN }}
      shell: bash
      run: |
        # transform the list of package names to multiple `--filter=<PACKAGE NAME>` arguments for pnpm
        PNPM_RELEASE_FILTER_ARGS=$(
          echo "${{ steps.releases.outputs.list-as-names-only || inputs.package-filter }}" | \
            sed 's/^/--filter=/' | \
            tr '\n' ' '
        )

        # Expose this flag as environment variable, so that packages can check for it during the release process
        export IS_MAIN_BREAKPROOF_REPO='${{steps.releases.outputs.is-main-breakproof-repo}}'

        # try to release affected packages
        # start from deepest dependencies to -> top level ones, bumping each version, releasing & pushing to git, unless it's a snapshot version
        # also add CI='false' to work around https://github.com/pnpm/pnpm/issues/9563
        # @see https://github.com/watson/ci-info/blob/54b034388e65347a87db396f44d5a95c79be0e0e/index.js#L36
        CI='false' ${{ inputs.snapshot && 'DEFAULT_RELEASE_IT_VERSIONING_STRATEGY=SNAPSHOT' }} pnpm $PNPM_RELEASE_FILTER_ARGS --workspace-concurrency=1 run release --ci -VV

    - name: Check if new commits were added
      shell: bash
      id: check-result
      run: |
        CURRENT_COMMIT=$(git rev-parse HEAD)
        TRIGGERED_COMMIT=${{ github.sha }}
        echo "$CURRENT_COMMIT $TRIGGERED_COMMIT"
        if [ "$CURRENT_COMMIT" == "$TRIGGERED_COMMIT" ]; then
           echo "No new commits"
           echo "new-commits=false" >> $GITHUB_OUTPUT
        else
          echo "New commits appeared - release was made"
          echo "new-commits=true" >> $GITHUB_OUTPUT
        fi
