name: Manually trigger release for specific packages
on:
  workflow_dispatch:
    inputs:
      package-filter:
        description: The pnpm filter/selector of packages you want to release
        required: true
        type: string
      ref:
        description:
          Name of the branch, tag or SHA hash you want to trigger a release
          from. Default value will derive new version from git commits. Anything
          different from the default value will trigger a snapshot release.
        default: ${{ github.event.repository.default_branch }}
        required: false
        type: string

concurrency:
  # same group as `_repo-on-change.yaml` workflow
  group: release-or-wait-until-release-is-done
  # wait previous releases to finish
  cancel-in-progress: false

#
# We transfer some secrets to env vars so we don't have to repeat them in reusable
# actions which unlike reusable workflows, can't inherit secrets
#
env:
  SECRET_NPM_REGISTRY_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_AUTH_TOKEN }}
  SECRET_NPM_REGISTRY_USER: ${{ secrets.NPM_REGISTRY_USER }}
  SECRET_NPM_REGISTRY_PASSWORD: ${{ secrets.NPM_REGISTRY_PASSWORD }}

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - name:
          ⚠️ YOU CAN'T TRIGGER AN OFFICIAL RELEASE OUTSIDE THE DEFAULT BRANCH ⚠️
        if:
          ${{ github.ref_name != github.event.repository.default_branch &&
          inputs.ref == github.event.repository.default_branch }}
        shell: bash
        run: |
          echo '## ⚠️ YOU CAN'"'"'T TRIGGER RELEASE OUTSIDE THE DEFAULT BRANCH ⚠️' >> "$GITHUB_STEP_SUMMARY"
          echo 'Release is only possible from the default branch' >> "$GITHUB_STEP_SUMMARY"
          exit 1

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.AUTORELEASE_BOT_TOKEN }}
          ref: ${{ inputs.ref }}

      - uses: ./.github/actions/setup-pnpm
        with:
          store-and-tasks-cache-package-filter: '${{ inputs.package-filter }}'
          task-cache-name: autorelease

      - uses: ./.github/actions/npm-login

      - uses: ./.github/actions/release
        with:
          AUTORELEASE_BOT_TOKEN: ${{ secrets.AUTORELEASE_BOT_TOKEN }}
          autorelease-bot-name: ${{ vars.AUTORELEASE_BOT_NAME }}
          autorelease-bot-email: ${{ vars.AUTORELEASE_BOT_EMAIL }}
          package-filter: '${{ inputs.package-filter }}'
          snapshot:
            ${{ inputs.ref == github.event.repository.default_branch && '' ||
            'true' }}
